# mkdocs.yml
site_name: ODE Docs

theme:
  name: "material"


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocstrings

nav:
  - ODE Docs: index.md
  - reference.md


